public class StudentInfo 
{
    public StudentInfo()
    {
        /*
        Student[] students = new Student[3];
        
        Student stdObj = new Student();
        stdObj.name = 'Student 1';
    	stdObj.email ='std1@gmail.com';
    	stdObj.age = 20;  
        
        students[0] = stdObj;
        
        Student stdObj1 = new Student();
        stdObj1.name = 'Student 2';
    	stdObj1.email ='std2@gmail.com';
    	stdObj1.age = 20;  
        
        students[1] = stdObj1;
        
        Student stdObj2 = new Student();
        stdObj2.name = 'Student 3';
    	stdObj2.email ='std3@gmail.com';
    	stdObj2.age = 20;  
        
        students[2] = stdObj2;
        
        for(Student iterator : students)
        {
            system.debug('Student Info '+iterator.name);
            system.debug('Student Info '+iterator.email);
            system.debug('Student Info '+iterator.age);
        }
		
        
        AccountInfo accInfoObj = new AccountInfo();
        
        accInfoObj.accountRecord = new Account(Name='TCS');
        //accInfoObj.accountRecord.Name = 'TCS';
        
        accInfoObj.flag = true;

        system.debug('Account Info '+accInfoObj.accountRecord);
        system.debug('Account Info '+accInfoObj.flag);      
        
        ContactData conDataObj = new ContactData();
        conDataObj.age = 20;
        conDataObj.email = 'abc@gmail.com';
        conDataObj.contactRecord = new Contact(LastName='Contact');
        
        system.debug('Contact Data '+conDataObj.contactRecord);
        system.debug('Contact Data '+conDataObj.age);      
        system.debug('Contact Data '+conDataObj.email);  
		
        List<String> aplaces = new List<String>{'A1','A2','A3','A4'};
        List<String> bplaces = new List<String>{'B1','B2','B3','B4'};
        List<String> cplaces = new List<String>{'C1','C2','C3','C4'};
        List<List<String>> places = new List<List<String>>{aplaces,bplaces,cplaces}; 
            for(String iterator : places.get(1))
        	{
                system.debug('Places at Index 1 '+iterator);
            }
		
        List<Account> accountList1 = new List<Account>{new Account(Name='TCS1',Industry='IT1',Rating='Hot1'),
            										   new Account(Name='TCS2',Industry='IT2',Rating='Hot2'),
            										   new Account(Name='TCS3',Industry='IT3',Rating='Hot3'),
            										   new Account(Name='TCS4',Industry='IT4',Rating='Hot4')};
                                                           
       	List<Account> accountList2 = new List<Account>{new Account(Name='ITC1',Industry='Healthcare1',Rating='Hot1'),
            										   new Account(Name='ITC2',Industry='Healthcare2',Rating='Hot2'),
            										   new Account(Name='ITC3',Industry='Healthcare3',Rating='Hot3'),
            										   new Account(Name='ITC4',Industry='Healthcare4',Rating='Hot4')};
                                                           
        
        List<List<Account>> accountList = new List<List<Account>>{accountList1,accountList2};
            for(Account iterator : accountList.get(1))
        	{
                system.debug('Account Records at Index 1 '+iterator.Name);
                system.debug('Account Records at Index 1 '+iterator.Industry);
				system.debug('Account Records at Index 1 '+iterator.Rating);
 
            }
		*/
        
        
               
    } 
}